apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: metrics-example
spec:
  jobLabel: metrics-example
  selector:
    matchLabels:
      app: metrics-example
  endpoints:
    - port: metrics
