# https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml

prometheus:
  ingress:
    enabled: true
    hosts:
      - prometheus.k8s.sikademo.com # --- PROMETHEUS DOMAIN ---
    paths:
      - /
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    tls:
    - secretName: prometheus-ingress-tls
      hosts:
      - prometheus.k8s.sikademo.com

grafana:
  ingress:
    enabled: true
    hosts:
      - grafana.k8s.sikademo.com # --- GRAFANA DOMAIN ---
    paths:
      - /
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    tls:
    - secretName: grafana-ingress-tls
      hosts:
      - grafana.k8s.sikademo.com

alertmanager:
  ingress:
    enabled: true
    hosts:
      - alertmanager.k8s.sikademo.com # --- ALERTMANAGER DOMAIN ---
    paths:
      - /
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    tls:
    - secretName: alertmanager-ingress-tls
      hosts:
      - alertmanager.k8s.sikademo.com
